SecRuleEngine On

SecRule ARGS "@contains <script>" \
"id:1001,\
phase:2,\
deny,\
status:403,\
msg:'XSS Attack Blocked'"

SecRule ARGS "@rx (?i:union.*select)" \
"id:1002,\
phase:2,\
deny,\
status:403,\
msg:'SQL Injection Blocked'"

SecRule REQUEST_URI "@contains ../" \
"id:1003,\
phase:2,\
deny,\
status:403,\
msg:'Directory Traversal Blocked'"
